### ISSUE TITLE
Create a "Down for Maintenance" page in Fast Tracker app

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/fast-tracker-tool#4]
### Summary
Need a way to communicate to users hitting page during maintenance window, why the app is down, and for how long

### How

- [ ] Create a standalone page within app - no links to or from
- [ ] Add relevant information - text and imagery
- [ ] Set as default page when taking app down for breaking updates
